version: '3'
services:
  httpd:
    container_name: httpd-container
    build: ./apache
    ports:
      - "80:80"
    depends_on:
      - "tomcat"

  tomcat:
    container_name: tomcat-container
    build: ./tomcat
    expose:
      - "8009"
    environment:
      TZ: Asia/Tokyo
