version: '3'
services:
  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    cap_add: # mbind: Operation not permitted
      - SYS_NICE

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  httpd:
    container_name: httpd-container
    build: ./apache
    ports:
      - "80:80"
    depends_on:
      - "tomcat"

  tomcat:
    container_name: tomcat-container
    build: ./tomcat
    expose:
      - "8009"
    environment:
      TZ: Asia/Tokyo
      CATALINA_OPTS: "-server -Xmx8192M -Xms8192M -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=1024M -Dfile.encoding=UTF-8"
